// GENERATED by design-workflow flutter adapter. Do not edit manually.
// Source: docs/adapter-examples/motion-set.json

import 'package:flutter/animation.dart';

class AppMotion {
  AppMotion._();
  static const instant = Duration(milliseconds: 0);
  static const fast = Duration(milliseconds: 150);
  static const normal = Duration(milliseconds: 250);
  static const slow = Duration(milliseconds: 400);
  static const enter = Duration(milliseconds: 300);
  static const exit = Duration(milliseconds: 200);
  static const press = Duration(milliseconds: 120);
  static const celebrate = Duration(milliseconds: 600);
}

class AppCurves {
  AppCurves._();
  static const instant = Curves.linear;
  static const fast = Curves.easeOut;
  static const normal = Curves.easeInOut;
  static const slow = Curves.easeInOut;
  static const enter = Curves.decelerate;
  static const exit = Curves.easeIn;
  static const press = Curves.easeOut;
  static const celebrate = Curves.elasticOut;
}
