// GENERATED by design-workflow flutter adapter. Do not edit manually.
// Source: docs/adapter-examples/palette.json
// Roles: 29

import 'package:flutter/material.dart';

class AppColors {
  AppColors._();

  static const _light = _AppColorsImpl(
    brandDefault: Color(0xFFC96442),
    brandMuted: Color(0xFFF5D4C5),
    brandPressed: Color(0xFFB35530),
    brandDisabled: Color(0xFFE9C5B6),
    brandOnColor: Color(0xFFFFFFFF),
    bgBase: Color(0xFFF5F4ED),
    bgSurface: Color(0xFFFFFFFF),
    bgSurfaceRaised: Color(0xFFFAFAF6),
    bgInput: Color(0xFFF0EFE8),
    bgOverlay: Color(0x00000099),
    bgSkeleton: Color(0xFFE8E7E0),
    borderDefault: Color(0xFFD9D8D2),
    borderStrong: Color(0xFFA3A29E),
    borderFocus: Color(0xFFC96442),
    textPrimary: Color(0xFF1A1A17),
    textSecondary: Color(0xFF595955),
    textMuted: Color(0xFF8E8D88),
    textOnBrand: Color(0xFFFFFFFF),
    feedbackSuccess: Color(0xFF2F6E3A),
    feedbackSuccessMuted: Color(0xFFD4ECD9),
    feedbackWarning: Color(0xFFB8731F),
    feedbackWarningMuted: Color(0xFFF4E3C4),
    feedbackError: Color(0xFFB8332F),
    feedbackErrorMuted: Color(0xFFF4D4D2),
    feedbackInfo: Color(0xFF2C5FA3),
    feedbackInfoMuted: Color(0xFFD2E1F2),
    gameAccent: Color(0xFF6A3FB5),
    gameAccentMuted: Color(0xFFE2D4F0),
    gameAccentOnColor: Color(0xFFFFFFFF)
  );

  static const _dark = _AppColorsImpl(
    brandDefault: Color(0xFFD97757),
    brandMuted: Color(0xFF5C3A2E),
    brandPressed: Color(0xFFC46141),
    brandDisabled: Color(0xFF4A2E25),
    brandOnColor: Color(0xFF1A0E08),
    bgBase: Color(0xFF141413),
    bgSurface: Color(0xFF1D1D1C),
    bgSurfaceRaised: Color(0xFF262625),
    bgInput: Color(0xFF232322),
    bgOverlay: Color(0x000000CC),
    bgSkeleton: Color(0xFF2D2D2C),
    borderDefault: Color(0xFF34332F),
    borderStrong: Color(0xFF5C5B56),
    borderFocus: Color(0xFFD97757),
    textPrimary: Color(0xFFF5F4ED),
    textSecondary: Color(0xFFA3A29C),
    textMuted: Color(0xFF6E6D68),
    textOnBrand: Color(0xFF1A0E08),
    feedbackSuccess: Color(0xFF5FB872),
    feedbackSuccessMuted: Color(0xFF1F3A25),
    feedbackWarning: Color(0xFFD99A40),
    feedbackWarningMuted: Color(0xFF3D2E15),
    feedbackError: Color(0xFFE06B66),
    feedbackErrorMuted: Color(0xFF3A1E1C),
    feedbackInfo: Color(0xFF5FA3E0),
    feedbackInfoMuted: Color(0xFF1A2E45),
    gameAccent: Color(0xFF9D7AD9),
    gameAccentMuted: Color(0xFF2D1E45),
    gameAccentOnColor: Color(0xFFF5F4ED)
  );

  static _AppColorsImpl of(BuildContext context) =>
      Theme.of(context).brightness == Brightness.dark ? _dark : _light;
}

class _AppColorsImpl {
  const _AppColorsImpl({
    required this.brandDefault,
    required this.brandMuted,
    required this.brandPressed,
    required this.brandDisabled,
    required this.brandOnColor,
    required this.bgBase,
    required this.bgSurface,
    required this.bgSurfaceRaised,
    required this.bgInput,
    required this.bgOverlay,
    required this.bgSkeleton,
    required this.borderDefault,
    required this.borderStrong,
    required this.borderFocus,
    required this.textPrimary,
    required this.textSecondary,
    required this.textMuted,
    required this.textOnBrand,
    required this.feedbackSuccess,
    required this.feedbackSuccessMuted,
    required this.feedbackWarning,
    required this.feedbackWarningMuted,
    required this.feedbackError,
    required this.feedbackErrorMuted,
    required this.feedbackInfo,
    required this.feedbackInfoMuted,
    required this.gameAccent,
    required this.gameAccentMuted,
    required this.gameAccentOnColor
  });

  final Color brandDefault;
  final Color brandMuted;
  final Color brandPressed;
  final Color brandDisabled;
  final Color brandOnColor;
  final Color bgBase;
  final Color bgSurface;
  final Color bgSurfaceRaised;
  final Color bgInput;
  final Color bgOverlay;
  final Color bgSkeleton;
  final Color borderDefault;
  final Color borderStrong;
  final Color borderFocus;
  final Color textPrimary;
  final Color textSecondary;
  final Color textMuted;
  final Color textOnBrand;
  final Color feedbackSuccess;
  final Color feedbackSuccessMuted;
  final Color feedbackWarning;
  final Color feedbackWarningMuted;
  final Color feedbackError;
  final Color feedbackErrorMuted;
  final Color feedbackInfo;
  final Color feedbackInfoMuted;
  final Color gameAccent;
  final Color gameAccentMuted;
  final Color gameAccentOnColor;
}

extension AppColorsX on BuildContext {
  _AppColorsImpl get colors => AppColors.of(this);
}
