// GENERATED by design-workflow flutter adapter. Do not edit manually.
// Source: docs/adapter-examples/widget-tree.json

import 'package:flutter/material.dart';

class RedeemCouponForm extends StatelessWidget {
  const RedeemCouponForm({super.key});

  @override
  Widget build(BuildContext context) {
    return AppFormGroup(
      variant: AppFormGroupVariant.stacked,
      size: AppFormGroupSize.md,
      title: 'Resgatar cupom',
      description: 'Cole o código que você recebeu por e-mail.',
      children: [
        AppInput(
          variant: AppInputVariant.text,
          size: AppInputSize.lg,
          name: 'couponCode',
          label: 'Código',
          placeholder: 'BRASA-2026',
          required: true,
          autocomplete: 'off',
        ),
        AppText(
          variant: AppTextVariant.helper,
          size: AppTextSize.sm,
          value: 'Maiúsculas e minúsculas contam.',
          tone: 'muted',
        ),
        AppButton(
          variant: AppButtonVariant.primary,
          size: AppButtonSize.lg,
          label: 'Resgatar',
          fullWidth: true,
          onPress: 'submitCoupon',
        ),
        AppButton(
          variant: AppButtonVariant.ghost,
          size: AppButtonSize.md,
          label: 'Cancelar',
          fullWidth: true,
          onPress: 'dismiss',
        ),
      ],
    );
  }
}
