// GENERATED by design-workflow nextjs-tailwind adapter. Do not edit manually.
// Source: docs/adapter-examples/widget-tree.json


export function RedeemCouponForm() {
  return (
    <form data-variant="stacked" title="Resgatar cupom" description="Cole o código que você recebeu por e-mail.">
      <input data-variant="text" name="couponCode" placeholder="BRASA-2026" required autocomplete="off">
        Código
      </input>
      <span data-variant="helper" tone="muted">
        Maiúsculas e minúsculas contam.
      </span>
      <button className="rounded-lg font-medium transition-colors bg-brand-default text-text-on-brand hover:bg-brand-pressed px-6 py-3 text-base w-full" fullWidth onPress="submitCoupon">
        Resgatar
      </button>
      <button className="rounded-lg font-medium transition-colors bg-transparent text-text-primary hover:bg-bg-surface px-5 py-2.5 text-base w-full" fullWidth onPress="dismiss">
        Cancelar
      </button>
    </form>
  );
}
