// GENERATED by design-workflow nextjs-tailwind adapter (shadcn variant). Do not edit manually.
// Source: docs/adapter-examples/widget-tree.json

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export function RedeemCouponForm() {
  return (
    <form data-variant="stacked" title="Resgatar cupom" description="Cole o código que você recebeu por e-mail.">
      <Input data-variant="text" size="lg" name="couponCode" placeholder="BRASA-2026" required autocomplete="off">
        Código
      </Input>
      <span data-variant="helper" tone="muted">
        Maiúsculas e minúsculas contam.
      </span>
      <Button variant="default" size="lg" fullWidth onPress="submitCoupon">
        Resgatar
      </Button>
      <Button variant="ghost" size="md" fullWidth onPress="dismiss">
        Cancelar
      </Button>
    </form>
  );
}
