// GENERATED by design-workflow react-native adapter. Do not edit manually.
// Source: docs/adapter-examples/motion-set.json

import { Easing, EasingFunction } from "react-native";

export type MotionRole =
  | "instant"
  | "fast"
  | "normal"
  | "slow"
  | "enter"
  | "exit"
  | "press"
  | "celebrate";;

export interface MotionToken {
  durationMs: number;
  easing: EasingFunction;
}

export const motion: Record<MotionRole, MotionToken> = {
  instant: { durationMs: 0, easing: Easing.linear },
  fast: { durationMs: 150, easing: Easing.out(Easing.ease) },
  normal: { durationMs: 250, easing: Easing.inOut(Easing.ease) },
  slow: { durationMs: 400, easing: Easing.inOut(Easing.ease) },
  enter: { durationMs: 300, easing: Easing.out(Easing.cubic) },
  exit: { durationMs: 200, easing: Easing.in(Easing.ease) },
  press: { durationMs: 120, easing: Easing.out(Easing.ease) },
  celebrate: { durationMs: 600, easing: Easing.elastic(1) },
};
