// GENERATED by design-workflow react-native adapter. Do not edit manually.
// Source: docs/adapter-examples/palette.json

export type ColorRole =
  | "brandDefault"
  | "brandMuted"
  | "brandPressed"
  | "brandDisabled"
  | "brandOnColor"
  | "bgBase"
  | "bgSurface"
  | "bgSurfaceRaised"
  | "bgInput"
  | "bgOverlay"
  | "bgSkeleton"
  | "borderDefault"
  | "borderStrong"
  | "borderFocus"
  | "textPrimary"
  | "textSecondary"
  | "textMuted"
  | "textOnBrand"
  | "feedbackSuccess"
  | "feedbackSuccessMuted"
  | "feedbackWarning"
  | "feedbackWarningMuted"
  | "feedbackError"
  | "feedbackErrorMuted"
  | "feedbackInfo"
  | "feedbackInfoMuted"
  | "gameAccent"
  | "gameAccentMuted"
  | "gameAccentOnColor";;

export type Palette = Record<ColorRole, string>;

export const lightColors: Palette = {
  brandDefault: "#c96442",
  brandMuted: "#f5d4c5",
  brandPressed: "#b35530",
  brandDisabled: "#e9c5b6",
  brandOnColor: "#ffffff",
  bgBase: "#f5f4ed",
  bgSurface: "#ffffff",
  bgSurfaceRaised: "#fafaf6",
  bgInput: "#f0efe8",
  bgOverlay: "#00000099",
  bgSkeleton: "#e8e7e0",
  borderDefault: "#d9d8d2",
  borderStrong: "#a3a29e",
  borderFocus: "#c96442",
  textPrimary: "#1a1a17",
  textSecondary: "#595955",
  textMuted: "#8e8d88",
  textOnBrand: "#ffffff",
  feedbackSuccess: "#2f6e3a",
  feedbackSuccessMuted: "#d4ecd9",
  feedbackWarning: "#b8731f",
  feedbackWarningMuted: "#f4e3c4",
  feedbackError: "#b8332f",
  feedbackErrorMuted: "#f4d4d2",
  feedbackInfo: "#2c5fa3",
  feedbackInfoMuted: "#d2e1f2",
  gameAccent: "#6a3fb5",
  gameAccentMuted: "#e2d4f0",
  gameAccentOnColor: "#ffffff",
};

export const darkColors: Palette = {
  brandDefault: "#d97757",
  brandMuted: "#5c3a2e",
  brandPressed: "#c46141",
  brandDisabled: "#4a2e25",
  brandOnColor: "#1a0e08",
  bgBase: "#141413",
  bgSurface: "#1d1d1c",
  bgSurfaceRaised: "#262625",
  bgInput: "#232322",
  bgOverlay: "#000000cc",
  bgSkeleton: "#2d2d2c",
  borderDefault: "#34332f",
  borderStrong: "#5c5b56",
  borderFocus: "#d97757",
  textPrimary: "#f5f4ed",
  textSecondary: "#a3a29c",
  textMuted: "#6e6d68",
  textOnBrand: "#1a0e08",
  feedbackSuccess: "#5fb872",
  feedbackSuccessMuted: "#1f3a25",
  feedbackWarning: "#d99a40",
  feedbackWarningMuted: "#3d2e15",
  feedbackError: "#e06b66",
  feedbackErrorMuted: "#3a1e1c",
  feedbackInfo: "#5fa3e0",
  feedbackInfoMuted: "#1a2e45",
  gameAccent: "#9d7ad9",
  gameAccentMuted: "#2d1e45",
  gameAccentOnColor: "#f5f4ed",
};

export const palettes = { light: lightColors, dark: darkColors };
export type PaletteMode = keyof typeof palettes;
