// GENERATED by design-workflow react-native adapter. Do not edit manually.
// Source: docs/adapter-examples/widget-tree.json

import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { useMemo } from "react";
import { useColors } from "@/theme/useColors";
import type { Palette } from "@/theme/colors";

export function RedeemCouponForm() {
  const colors = useColors();
  const styles = useMemo(() => makeStyles(colors), [colors]);
  return (
    <View style={styles.stacked_1} data-variant="stacked" title="Resgatar cupom" description="Cole o código que você recebeu por e-mail.">
      <View style={styles.input_field_3}>
        <Text style={styles.input_label_4}>Código</Text>
        <TextInput style={styles.text_2} data-variant="text" name="couponCode" placeholder="BRASA-2026" required autocomplete="off" />
      </View>
      <Text style={styles.helper_5}>
        Maiúsculas e minúsculas contam.
      </Text>
      <Pressable style={styles.primary_6} onPress="submitCoupon">
        <Text style={styles.button_label_7}>Resgatar</Text>
      </Pressable>
      <Pressable style={styles.ghost_8} onPress="dismiss">
        <Text style={styles.button_label_9}>Cancelar</Text>
      </Pressable>
    </View>
  );
}

const makeStyles = (colors: Palette) => StyleSheet.create({
  stacked_1: {
    gap: 8,
  },
  text_2: {
    borderWidth: 1,
    borderColor: colors.borderDefault,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: colors.textPrimary,
    backgroundColor: colors.bgInput,
  },
  input_field_3: {
    gap: 4,
  },
  input_label_4: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: "500",
  },
  helper_5: {
    color: colors.textMuted,
  },
  primary_6: {
    backgroundColor: colors.brandDefault,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "stretch",
  },
  button_label_7: {
    color: colors.textOnBrand,
    fontSize: 16,
    fontWeight: "500",
  },
  ghost_8: {
    backgroundColor: "transparent",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "stretch",
  },
  button_label_9: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "500",
  },
});
